/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  ApiResponse,
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  GetInventory200,
  LoginUserParams,
  Order,
  Pet,
  UpdatePetWithFormParams,
  UploadFileParams,
  User,
} from './model';

export const getSwaggerPetstoreOpenAPI30 = () => {
  /**
   * Update an existing pet by Id.
   * @summary Update an existing pet.
   */
  const updatePet = <TData = AxiosResponse<Pet>>(
    pet: Pet,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`https://api.store.local/pet`, pet, options);
  };

  /**
   * Add a new pet to the store.
   * @summary Add a new pet to the store.
   */
  const addPet = <TData = AxiosResponse<Pet>>(
    pet: Pet,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/pet`, pet, options);
  };

  /**
   * Multiple status values can be provided with comma separated strings.
   * @summary Finds Pets by status.
   */
  const findPetsByStatus = <TData = AxiosResponse<Pet[]>>(
    params: FindPetsByStatusParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/pet/findByStatus`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   * @summary Finds Pets by tags.
   */
  const findPetsByTags = <TData = AxiosResponse<Pet[]>>(
    params: FindPetsByTagsParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/pet/findByTags`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Returns a single pet.
   * @summary Find pet by ID.
   */
  const getPetById = <TData = AxiosResponse<Pet>>(
    petId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/pet/${petId}`, options);
  };

  /**
   * Updates a pet resource based on the form data.
   * @summary Updates a pet in the store with form data.
   */
  const updatePetWithForm = <TData = AxiosResponse<Pet>>(
    petId: number,
    params?: UpdatePetWithFormParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/pet/${petId}`, undefined, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Delete a pet.
   * @summary Deletes a pet.
   */
  const deletePet = <TData = AxiosResponse<void>>(
    petId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://api.store.local/pet/${petId}`, options);
  };

  /**
   * Upload image of the pet.
   * @summary Uploads an image.
   */
  const uploadFile = <TData = AxiosResponse<ApiResponse>>(
    petId: number,
    uploadFileBody: Blob,
    params?: UploadFileParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/pet/${petId}/uploadImage`, uploadFileBody, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Returns a map of status codes to quantities.
   * @summary Returns pet inventories by status.
   */
  const getInventory = <TData = AxiosResponse<GetInventory200>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/store/inventory`, options);
  };

  /**
   * Place a new order in the store.
   * @summary Place an order for a pet.
   */
  const placeOrder = <TData = AxiosResponse<Order>>(
    order: Order,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/store/order`, order, options);
  };

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * @summary Find purchase order by ID.
   */
  const getOrderById = <TData = AxiosResponse<Order>>(
    orderId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/store/order/${orderId}`, options);
  };

  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
   * @summary Delete purchase order by identifier.
   */
  const deleteOrder = <TData = AxiosResponse<void>>(
    orderId: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://api.store.local/store/order/${orderId}`, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Create user.
   */
  const createUser = <TData = AxiosResponse<User>>(
    user: User,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/user`, user, options);
  };

  /**
   * Creates list of users with given input array.
   * @summary Creates list of users with given input array.
   */
  const createUsersWithListInput = <TData = AxiosResponse<User>>(
    user: User[],
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`https://api.store.local/user/createWithList`, user, options);
  };

  /**
   * Log into the system.
   * @summary Logs user into the system.
   */
  const loginUser = <TData = AxiosResponse<string>>(
    params?: LoginUserParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/user/login`, {
      responseType: 'text',
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Log user out of the system.
   * @summary Logs out current logged in user session.
   */
  const logoutUser = <TData = AxiosResponse<void>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/user/logout`, options);
  };

  /**
   * Get user detail based on username.
   * @summary Get user by user name.
   */
  const getUserByName = <TData = AxiosResponse<User>>(
    username: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`https://api.store.local/user/${username}`, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Update user resource.
   */
  const updateUser = <TData = AxiosResponse<void>>(
    username: string,
    user: User,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`https://api.store.local/user/${username}`, user, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Delete user resource.
   */
  const deleteUser = <TData = AxiosResponse<void>>(
    username: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`https://api.store.local/user/${username}`, options);
  };

  return {
    updatePet,
    addPet,
    findPetsByStatus,
    findPetsByTags,
    getPetById,
    updatePetWithForm,
    deletePet,
    uploadFile,
    getInventory,
    placeOrder,
    getOrderById,
    deleteOrder,
    createUser,
    createUsersWithListInput,
    loginUser,
    logoutUser,
    getUserByName,
    updateUser,
    deleteUser,
  };
};
export type UpdatePetResult = AxiosResponse<Pet>;
export type AddPetResult = AxiosResponse<Pet>;
export type FindPetsByStatusResult = AxiosResponse<Pet[]>;
export type FindPetsByTagsResult = AxiosResponse<Pet[]>;
export type GetPetByIdResult = AxiosResponse<Pet>;
export type UpdatePetWithFormResult = AxiosResponse<Pet>;
export type DeletePetResult = AxiosResponse<void>;
export type UploadFileResult = AxiosResponse<ApiResponse>;
export type GetInventoryResult = AxiosResponse<GetInventory200>;
export type PlaceOrderResult = AxiosResponse<Order>;
export type GetOrderByIdResult = AxiosResponse<Order>;
export type DeleteOrderResult = AxiosResponse<void>;
export type CreateUserResult = AxiosResponse<User>;
export type CreateUsersWithListInputResult = AxiosResponse<User>;
export type LoginUserResult = AxiosResponse<string>;
export type LogoutUserResult = AxiosResponse<void>;
export type GetUserByNameResult = AxiosResponse<User>;
export type UpdateUserResult = AxiosResponse<void>;
export type DeleteUserResult = AxiosResponse<void>;
